//! Callback infrastructure for hooking into LangChain execution lifecycles.
//!
//! Provides the [`CallbackHandler`] trait, a [`CallbackManager`] that
//! dispatches events to registered handlers, and built-in handlers like
//! [`StdOutCallbackHandler`].

use serde_json::Value;
use std::sync::Arc;

/// Trait for handling lifecycle events during LangChain execution.
///
/// All methods have default no-op implementations. Override only the events
/// you care about.
pub trait CallbackHandler: Send + Sync {
    /// Called when a chain run starts.
    fn on_chain_start(&self, name: &str, inputs: &Value) {
        let _ = (name, inputs);
    }
    /// Called when a chain run finishes successfully.
    fn on_chain_end(&self, name: &str, outputs: &Value) {
        let _ = (name, outputs);
    }
    /// Called when a chain run encounters an error.
    fn on_chain_error(&self, name: &str, error: &Value) {
        let _ = (name, error);
    }
    /// Called when an LLM starts processing prompts.
    fn on_llm_start(&self, name: &str, prompts: &[String]) {
        let _ = (name, prompts);
    }
    /// Called for each new token generated by an LLM during streaming.
    fn on_llm_new_token(&self, token: &str) {
        let _ = token;
    }
    /// Called when an LLM finishes generating.
    fn on_llm_end(&self, name: &str, output: &Value) {
        let _ = (name, output);
    }
    /// Called when an LLM encounters an error.
    fn on_llm_error(&self, name: &str, error: &Value) {
        let _ = (name, error);
    }
    /// Called when a tool starts execution.
    fn on_tool_start(&self, name: &str, input: &Value) {
        let _ = (name, input);
    }
    /// Called when a tool finishes successfully.
    fn on_tool_end(&self, name: &str, output: &Value) {
        let _ = (name, output);
    }
    /// Called when a tool encounters an error.
    fn on_tool_error(&self, name: &str, error: &Value) {
        let _ = (name, error);
    }
    /// Called for general text logging.
    fn on_text(&self, text: &str) {
        let _ = text;
    }
    /// Called when an agent takes an action.
    fn on_agent_action(&self, action: &Value) {
        let _ = action;
    }
    /// Called when an agent finishes.
    fn on_agent_finish(&self, finish: &Value) {
        let _ = finish;
    }
    /// Called when a retry attempt is made.
    fn on_retry(&self, name: &str, attempt: usize, error: &Value) {
        let _ = (name, attempt, error);
    }
}

/// A base callback handler with a name and verbose flag.
///
/// All event methods are no-ops; subclass and override as needed.
#[derive(Clone)]
pub struct BaseCallbackHandler {
    /// Human-readable name for this handler.
    pub name: String,
    /// Whether this handler should produce verbose output.
    pub always_verbose: bool,
}

impl BaseCallbackHandler {
    /// Creates a new `BaseCallbackHandler`.
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            always_verbose: false,
        }
    }

    /// Sets the verbose flag (builder pattern).
    pub fn with_verbose(mut self, verbose: bool) -> Self {
        self.always_verbose = verbose;
        self
    }
}

impl CallbackHandler for BaseCallbackHandler {
    fn on_chain_start(&self, _name: &str, _inputs: &Value) {}
    fn on_chain_end(&self, _name: &str, _outputs: &Value) {}
    fn on_chain_error(&self, _name: &str, _error: &Value) {}
    fn on_llm_start(&self, _name: &str, _prompts: &[String]) {}
    fn on_llm_new_token(&self, _token: &str) {}
    fn on_llm_end(&self, _name: &str, _output: &Value) {}
    fn on_llm_error(&self, _name: &str, _error: &Value) {}
    fn on_tool_start(&self, _name: &str, _input: &Value) {}
    fn on_tool_end(&self, _name: &str, _output: &Value) {}
    fn on_tool_error(&self, _name: &str, _error: &Value) {}
    fn on_text(&self, _text: &str) {}
    fn on_agent_action(&self, _action: &Value) {}
    fn on_agent_finish(&self, _finish: &Value) {}
    fn on_retry(&self, _name: &str, _attempt: usize, _error: &Value) {}
}

/// Dispatches lifecycle events to a collection of registered
/// [`CallbackHandler`]s.
pub struct CallbackManager {
    handlers: Vec<Arc<dyn CallbackHandler>>,
}

impl std::fmt::Debug for CallbackManager {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CallbackManager")
            .field("handler_count", &self.handlers.len())
            .finish()
    }
}

impl Clone for CallbackManager {
    fn clone(&self) -> Self {
        Self {
            handlers: self.handlers.clone(),
        }
    }
}

impl CallbackManager {
    /// Creates an empty callback manager.
    pub fn new() -> Self {
        Self {
            handlers: Vec::new(),
        }
    }

    /// Adds a handler to the manager.
    pub fn add_handler(&mut self, handler: Arc<dyn CallbackHandler>) {
        self.handlers.push(handler);
    }

    /// Adds a handler and returns `self` (builder pattern).
    pub fn with_handler(mut self, handler: Arc<dyn CallbackHandler>) -> Self {
        self.handlers.push(handler);
        self
    }

    /// Dispatches `on_chain_start` to all handlers.
    pub fn on_chain_start(&self, name: &str, inputs: &Value) {
        for handler in &self.handlers {
            handler.on_chain_start(name, inputs);
        }
    }

    /// Dispatches `on_chain_end` to all handlers.
    pub fn on_chain_end(&self, name: &str, outputs: &Value) {
        for handler in &self.handlers {
            handler.on_chain_end(name, outputs);
        }
    }

    /// Dispatches `on_chain_error` to all handlers.
    pub fn on_chain_error(&self, name: &str, error: &Value) {
        for handler in &self.handlers {
            handler.on_chain_error(name, error);
        }
    }

    /// Dispatches `on_llm_start` to all handlers.
    pub fn on_llm_start(&self, name: &str, prompts: &[String]) {
        for handler in &self.handlers {
            handler.on_llm_start(name, prompts);
        }
    }

    /// Dispatches `on_llm_new_token` to all handlers.
    pub fn on_llm_new_token(&self, token: &str) {
        for handler in &self.handlers {
            handler.on_llm_new_token(token);
        }
    }

    /// Dispatches `on_llm_end` to all handlers.
    pub fn on_llm_end(&self, name: &str, output: &Value) {
        for handler in &self.handlers {
            handler.on_llm_end(name, output);
        }
    }

    /// Dispatches `on_llm_error` to all handlers.
    pub fn on_llm_error(&self, name: &str, error: &Value) {
        for handler in &self.handlers {
            handler.on_llm_error(name, error);
        }
    }

    /// Dispatches `on_tool_start` to all handlers.
    pub fn on_tool_start(&self, name: &str, input: &Value) {
        for handler in &self.handlers {
            handler.on_tool_start(name, input);
        }
    }

    /// Dispatches `on_tool_end` to all handlers.
    pub fn on_tool_end(&self, name: &str, output: &Value) {
        for handler in &self.handlers {
            handler.on_tool_end(name, output);
        }
    }

    /// Dispatches `on_tool_error` to all handlers.
    pub fn on_tool_error(&self, name: &str, error: &Value) {
        for handler in &self.handlers {
            handler.on_tool_error(name, error);
        }
    }

    /// Dispatches `on_text` to all handlers.
    pub fn on_text(&self, text: &str) {
        for handler in &self.handlers {
            handler.on_text(text);
        }
    }

    /// Dispatches `on_agent_action` to all handlers.
    pub fn on_agent_action(&self, action: &Value) {
        for handler in &self.handlers {
            handler.on_agent_action(action);
        }
    }

    /// Dispatches `on_agent_finish` to all handlers.
    pub fn on_agent_finish(&self, finish: &Value) {
        for handler in &self.handlers {
            handler.on_agent_finish(finish);
        }
    }

    /// Dispatches `on_retry` to all handlers.
    pub fn on_retry(&self, name: &str, attempt: usize, error: &Value) {
        for handler in &self.handlers {
            handler.on_retry(name, attempt, error);
        }
    }
}

impl Default for CallbackManager {
    fn default() -> Self {
        Self::new()
    }
}

/// A no-op callback handler that ignores all events.
#[derive(Debug, Clone)]
pub struct EmptyCallbackHandler;

impl CallbackHandler for EmptyCallbackHandler {}

/// A callback handler that prints events to stdout for debugging.
#[derive(Debug, Clone)]
pub struct StdOutCallbackHandler;

impl CallbackHandler for StdOutCallbackHandler {
    fn on_chain_start(&self, name: &str, inputs: &Value) {
        println!("[chain:{}] started with inputs: {}", name, inputs);
    }

    fn on_chain_end(&self, name: &str, outputs: &Value) {
        println!("[chain:{}] finished with outputs: {}", name, outputs);
    }

    fn on_chain_error(&self, name: &str, error: &Value) {
        println!("[chain:{}] error: {}", name, error);
    }

    fn on_llm_start(&self, name: &str, prompts: &[String]) {
        println!("[llm:{}] started with {} prompts", name, prompts.len());
    }

    fn on_llm_new_token(&self, token: &str) {
        print!("{}", token);
    }

    fn on_llm_end(&self, name: &str, output: &Value) {
        println!("\n[llm:{}] finished: {}", name, output);
    }

    fn on_llm_error(&self, name: &str, error: &Value) {
        println!("[llm:{}] error: {}", name, error);
    }

    fn on_tool_start(&self, name: &str, input: &Value) {
        println!("[tool:{}] started with input: {}", name, input);
    }

    fn on_tool_end(&self, name: &str, output: &Value) {
        println!("[tool:{}] finished with output: {}", name, output);
    }

    fn on_tool_error(&self, name: &str, error: &Value) {
        println!("[tool:{}] error: {}", name, error);
    }

    fn on_text(&self, text: &str) {
        println!("[text] {}", text);
    }

    fn on_agent_action(&self, action: &Value) {
        println!("[agent] action: {}", action);
    }

    fn on_agent_finish(&self, finish: &Value) {
        println!("[agent] finished: {}", finish);
    }

    fn on_retry(&self, name: &str, attempt: usize, error: &Value) {
        println!("[retry:{}] attempt {} failed: {}", name, attempt, error);
    }
}

/// Convenience alias for an `Arc<dyn CallbackHandler>`.
pub type BoxCallbackHandler = Arc<dyn CallbackHandler>;
