//! Message types for chat-based interactions with LLMs.
//!
//! Provides [`BaseMessage`] — the core message struct — along with typed
//! wrappers ([`HumanMessage`], [`AIMessage`], [`SystemMessage`], etc.) and
//! supporting types for tool/function calls and chat prompt values.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use uuid::Uuid;

/// The role / origin of a message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MessageType {
    /// A message from a human user.
    Human,
    /// A message generated by an AI model.
    AI,
    /// A system-level instruction message.
    System,
    /// A message representing a tool's output.
    Tool,
    /// A message representing a function call/response.
    Function,
    /// A generic fallback message type.
    Generic,
    /// A chat message with a custom type.
    Chat,
}

/// Core message struct containing content, role, metadata, and identifiers.
///
/// Every message in the framework is built on `BaseMessage`. Use the typed
/// wrappers ([`HumanMessage`], [`AIMessage`], etc.) for convenience.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BaseMessage {
    /// The text content of the message.
    pub content: String,
    /// The role / origin of this message.
    #[serde(rename = "type")]
    pub message_type: MessageType,
    /// An optional name for the message sender.
    pub name: Option<String>,
    /// Extra key-value data attached to the message.
    pub additional_kwargs: HashMap<String, Value>,
    /// A unique identifier for this message.
    pub id: Uuid,
    /// Arbitrary metadata associated with this message.
    pub metadata: HashMap<String, Value>,
}

impl BaseMessage {
    /// Creates a new `BaseMessage` with the given content and type.
    ///
    /// A random UUID is generated for the `id` field. All other optional
    /// fields default to `None` or empty.
    pub fn new(content: impl Into<String>, message_type: MessageType) -> Self {
        Self {
            content: content.into(),
            message_type,
            name: None,
            additional_kwargs: HashMap::new(),
            id: Uuid::new_v4(),
            metadata: HashMap::new(),
        }
    }

    /// Sets the `name` field and returns `self` (builder pattern).
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }

    /// Sets the `additional_kwargs` field and returns `self`.
    pub fn with_additional_kwargs(mut self, kwargs: HashMap<String, Value>) -> Self {
        self.additional_kwargs = kwargs;
        self
    }

    /// Sets the `metadata` field and returns `self`.
    pub fn with_metadata(mut self, metadata: HashMap<String, Value>) -> Self {
        self.metadata = metadata;
        self
    }
}

/// Macro to generate a typed message wrapper struct.
///
/// Each generated struct wraps a [`BaseMessage`], sets the corresponding
/// [`MessageType`] variant, and implements `From` conversions plus
/// `Deref`/`DerefMut` so callers can access the underlying fields directly.
macro_rules! message_struct {
    ($name:ident, $variant:ident) => {
        /// Typed message wrapper.
        ///
        /// Automatically sets [`MessageType`] to
        #[doc = concat!("[`MessageType::", stringify!($variant), "`].")]
        #[derive(Debug, Clone, Serialize, Deserialize)]
        pub struct $name {
            /// The underlying [`BaseMessage`].
            pub message: BaseMessage,
        }

        impl $name {
            /// Creates a new typed message with the given content.
            pub fn new(content: impl Into<String>) -> Self {
                Self {
                    message: BaseMessage::new(content, MessageType::$variant),
                }
            }
        }

        impl From<BaseMessage> for $name {
            fn from(msg: BaseMessage) -> Self {
                Self { message: msg }
            }
        }

        impl From<$name> for BaseMessage {
            fn from(msg: $name) -> Self {
                msg.message
            }
        }

        impl std::ops::Deref for $name {
            type Target = BaseMessage;

            fn deref(&self) -> &Self::Target {
                &self.message
            }
        }

        impl std::ops::DerefMut for $name {
            fn deref_mut(&mut self) -> &mut Self::Target {
                &mut self.message
            }
        }
    };
}

message_struct!(HumanMessage, Human);
message_struct!(AIMessage, AI);
message_struct!(SystemMessage, System);
message_struct!(ToolMessage, Tool);
message_struct!(FunctionMessage, Function);
message_struct!(ChatMessage, Chat);

/// Represents a request to invoke a tool, as returned by an LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// A unique identifier for this tool call.
    pub id: String,
    /// The name of the tool to invoke.
    pub name: String,
    /// The arguments to pass to the tool, as a JSON value.
    pub args: Value,
}

impl ToolCall {
    /// Creates a new `ToolCall`.
    pub fn new(id: impl Into<String>, name: impl Into<String>, args: Value) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            args,
        }
    }
}

/// Represents a function call request from an LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// The name of the function to call.
    pub name: String,
    /// The JSON-encoded arguments string.
    pub arguments: String,
}

impl FunctionCall {
    /// Creates a new `FunctionCall`.
    pub fn new(name: impl Into<String>, arguments: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            arguments: arguments.into(),
        }
    }
}

/// A value object holding a vector of [`BaseMessage`]s, produced by chat prompt
/// templates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatPromptValue {
    /// The list of messages forming the prompt.
    pub messages: Vec<BaseMessage>,
}

impl ChatPromptValue {
    /// Creates a new `ChatPromptValue` from a list of messages.
    pub fn new(messages: Vec<BaseMessage>) -> Self {
        Self { messages }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_base_message_new() {
        let msg = BaseMessage::new("hello", MessageType::Human);
        assert_eq!(msg.content, "hello");
        assert!(matches!(msg.message_type, MessageType::Human));
        assert!(msg.name.is_none());
    }

    #[test]
    fn test_base_message_all_types() {
        let types = vec![
            (MessageType::Human, "Human"),
            (MessageType::AI, "AI"),
            (MessageType::System, "System"),
            (MessageType::Tool, "Tool"),
            (MessageType::Function, "Function"),
            (MessageType::Generic, "Generic"),
            (MessageType::Chat, "Chat"),
        ];
        for (ty, _) in types {
            let msg = BaseMessage::new("test", ty);
            assert_eq!(msg.content, "test");
        }
    }

    #[test]
    fn test_base_message_with_name() {
        let mut msg = BaseMessage::new("content", MessageType::AI);
        msg.name = Some("assistant".into());
        assert_eq!(msg.name.as_deref(), Some("assistant"));
    }

    #[test]
    fn test_base_message_serde() {
        let msg = BaseMessage::new("hello", MessageType::Human);
        let json = serde_json::to_string(&msg).unwrap();
        let deserialized: BaseMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.content, "hello");
        assert!(matches!(deserialized.message_type, MessageType::Human));
    }

    #[test]
    fn test_base_message_unique_ids() {
        let msg1 = BaseMessage::new("a", MessageType::Human);
        let msg2 = BaseMessage::new("b", MessageType::Human);
        assert_ne!(msg1.id, msg2.id);
    }

    #[test]
    fn test_human_message_new() {
        let msg = HumanMessage::new("hello");
        assert_eq!(msg.content, "hello");
        assert!(matches!(msg.message_type, MessageType::Human));
    }

    #[test]
    fn test_human_message_into_base() {
        let human = HumanMessage::new("hello");
        let base: BaseMessage = human.into();
        assert_eq!(base.content, "hello");
        assert!(matches!(base.message_type, MessageType::Human));
    }

    #[test]
    fn test_base_into_human_message() {
        let base = BaseMessage::new("hello", MessageType::Human);
        let human: HumanMessage = base.into();
        assert_eq!(human.content, "hello");
    }

    #[test]
    fn test_ai_message_new() {
        let ai = AIMessage::new("answer");
        assert_eq!(ai.content, "answer");
        assert!(matches!(ai.message_type, MessageType::AI));
    }

    #[test]
    fn test_system_message_new() {
        let sys = SystemMessage::new("instruction");
        assert_eq!(sys.content, "instruction");
        assert!(matches!(sys.message_type, MessageType::System));
    }

    #[test]
    fn test_tool_call_new() {
        let tc = ToolCall::new("call-1", "search", serde_json::json!({"q": "test"}));
        assert_eq!(tc.id, "call-1");
        assert_eq!(tc.name, "search");
    }

    #[test]
    fn test_function_call_new() {
        let fc = FunctionCall::new("search", r#"{"q": "test"}"#);
        assert_eq!(fc.name, "search");
        assert_eq!(fc.arguments, r#"{"q": "test"}"#);
    }

    #[test]
    fn test_chat_prompt_value_new() {
        let msgs = vec![BaseMessage::new("msg", MessageType::Human)];
        let cpv = ChatPromptValue::new(msgs);
        assert_eq!(cpv.messages.len(), 1);
    }

    #[test]
    fn test_message_type_serde() {
        let json = r#""Human""#;
        let mt: MessageType = serde_json::from_str(json).unwrap();
        assert!(matches!(mt, MessageType::Human));
    }

    #[test]
    fn test_message_type_display() {
        assert_eq!(format!("{:?}", MessageType::Human), "Human");
        assert_eq!(format!("{:?}", MessageType::AI), "AI");
    }

    #[test]
    fn test_messages_send_sync() {
        fn assert_send<T: Send>() {}
        fn assert_sync<T: Sync>() {}
        assert_send::<BaseMessage>();
        assert_sync::<BaseMessage>();
        assert_send::<HumanMessage>();
        assert_sync::<HumanMessage>();
        assert_send::<AIMessage>();
        assert_sync::<AIMessage>();
        assert_send::<SystemMessage>();
        assert_sync::<SystemMessage>();
    }
}
