//! Embedding provider implementations.
//!
//! Each module is gated behind a feature flag and implements the
//! [`Embeddings`](crate::traits::Embeddings) trait.

#[cfg(feature = "cache_backed")]
pub mod cache_backed;
#[cfg(feature = "fastembed")]
pub mod fastembed;
#[cfg(feature = "sentence_transformer")]
pub mod sentence_transformer;
#[cfg(feature = "self_hosted")]
pub mod self_hosted;
#[cfg(feature = "self_hosted_huggingface")]
pub mod self_hosted_huggingface;
#[cfg(feature = "self_hosted_llama")]
pub mod self_hosted_llama;
#[cfg(feature = "tensorflowhub")]
pub mod tensorflowhub;
#[cfg(feature = "everyscale")]
pub mod everyscale;
#[cfg(feature = "bookend")]
pub mod bookend;
#[cfg(feature = "clarifai")]
pub mod clarifai;
#[cfg(feature = "providers_cohere")]
pub mod cohere;
#[cfg(feature = "watsonx")]
pub mod watsonx;
#[cfg(feature = "deepinfra")]
pub mod deepinfra;
#[cfg(feature = "gradient")]
pub mod gradient;
#[cfg(feature = "huggingface_inference")]
pub mod huggingface_inference;
#[cfg(feature = "johnsnowlabs")]
pub mod johnsnowlabs;
#[cfg(feature = "providers_llamacpp")]
pub mod llamacpp;
#[cfg(feature = "providers_ollama")]
pub mod ollama;
#[cfg(feature = "spacy")]
pub mod spacy;
#[cfg(feature = "xinference")]
pub mod xinference;
#[cfg(feature = "providers_bedrock_titan")]
pub mod bedrock_titan;
#[cfg(feature = "providers_bedrock_cohere")]
pub mod bedrock_cohere;
#[cfg(feature = "providers_bedrock_mistral")]
pub mod bedrock_mistral;
#[cfg(feature = "providers_bedrock_llama")]
pub mod bedrock_llama;
#[cfg(feature = "providers_bedrock_stabilityai")]
pub mod bedrock_stabilityai;
#[cfg(feature = "providers_bedrock_amazon")]
pub mod bedrock_amazon;
#[cfg(feature = "providers_bedrock_anthropic")]
pub mod bedrock_anthropic;
#[cfg(feature = "providers_azure_openai")]
pub mod azure_openai;
#[cfg(feature = "providers_aws_sagemaker")]
pub mod aws_sagemaker;
#[cfg(feature = "providers_google_vertexai")]
pub mod google_vertexai;
#[cfg(feature = "providers_google_palm")]
pub mod google_palm;
#[cfg(feature = "providers_dashscope")]
pub mod dashscope;
#[cfg(feature = "providers_minimax")]
pub mod minimax;
#[cfg(feature = "providers_reka")]
pub mod reka;
#[cfg(feature = "providers_writer")]
pub mod writer;
#[cfg(feature = "alibaba_text")]
pub mod alibaba_text;
#[cfg(feature = "anthropic")]
pub mod anthropic;
#[cfg(feature = "ark")]
pub mod ark;
#[cfg(feature = "astra")]
pub mod astra;
#[cfg(feature = "baidu_ernie")]
pub mod baidu_ernie;
#[cfg(feature = "baidu_qianfan")]
pub mod baidu_qianfan;
#[cfg(feature = "baichuan")]
pub mod baichuan;
#[cfg(feature = "bedrock_ai21")]
pub mod bedrock_ai21;
#[cfg(feature = "bedrock_jurassic")]
pub mod bedrock_jurassic;
#[cfg(feature = "bedrock_titan_multimodal")]
pub mod bedrock_titan_multimodal;
#[cfg(feature = "cerebras")]
pub mod cerebras;
#[cfg(feature = "databricks_embed")]
pub mod databricks_embed;
#[cfg(feature = "engram")]
pub mod engram;
#[cfg(feature = "ernie")]
pub mod ernie;
#[cfg(feature = "fastembed_v2")]
pub mod fastembed_v2;
#[cfg(feature = "fire_embed")]
pub mod fire_embed;
#[cfg(feature = "fireworks_embed")]
pub mod fireworks_embed;
#[cfg(feature = "google_gecko")]
pub mod google_gecko;
#[cfg(feature = "google_multimodal")]
pub mod google_multimodal;
#[cfg(feature = "groq_embed")]
pub mod groq_embed;
#[cfg(feature = "gte")]
pub mod gte;
#[cfg(feature = "gte_small")]
pub mod gte_small;
#[cfg(feature = "huggingface_instruct")]
pub mod huggingface_instruct;
#[cfg(feature = "huggingface_sentence")]
pub mod huggingface_sentence;
#[cfg(feature = "octoai_embed")]
pub mod octoai_embed;
#[cfg(feature = "alibaba_vector")]
pub mod alibaba_vector;
#[cfg(feature = "anthropic_latest")]
pub mod anthropic_latest;
#[cfg(feature = "aws_bedrock_claude")]
pub mod aws_bedrock_claude;
#[cfg(feature = "aws_bedrock_mistral")]
pub mod aws_bedrock_mistral;
#[cfg(feature = "aws_bedrock_cohere_v2")]
pub mod aws_bedrock_cohere_v2;
#[cfg(feature = "aws_bedrock_llama_v2")]
pub mod aws_bedrock_llama_v2;
#[cfg(feature = "aws_bedrock_titan_v2")]
pub mod aws_bedrock_titan_v2;
#[cfg(feature = "azure_cognitive")]
pub mod azure_cognitive;
#[cfg(feature = "baidu_bce")]
pub mod baidu_bce;
#[cfg(feature = "bedrock_amazon_titan")]
pub mod bedrock_amazon_titan;
#[cfg(feature = "bedrock_ai21_jurassic")]
pub mod bedrock_ai21_jurassic;
#[cfg(feature = "bedrock_stabilityai_v2")]
pub mod bedrock_stabilityai_v2;
#[cfg(feature = "cohere_english")]
pub mod cohere_english;
#[cfg(feature = "cohere_multilingual")]
pub mod cohere_multilingual;
#[cfg(feature = "deepinfra_v2")]
pub mod deepinfra_v2;
#[cfg(feature = "deepseek_v2_embed")]
pub mod deepseek_v2_embed;
#[cfg(feature = "fireworks_v2_embed")]
pub mod fireworks_v2_embed;
#[cfg(feature = "google_gecko_v2")]
pub mod google_gecko_v2;
#[cfg(feature = "google_multimodal_v2")]
pub mod google_multimodal_v2;
#[cfg(feature = "google_vertexai_v3")]
pub mod google_vertexai_v3;
#[cfg(feature = "alibaba_dashscope")]
pub mod alibaba_dashscope;
#[cfg(feature = "alibaba_gte")]
pub mod alibaba_gte;
#[cfg(feature = "alibaba_gte_qwen")]
pub mod alibaba_gte_qwen;
#[cfg(feature = "alibaba_text_embedding")]
pub mod alibaba_text_embedding;
#[cfg(feature = "amazon_nova")]
pub mod amazon_nova;
#[cfg(feature = "amazon_titan_multimodal")]
pub mod amazon_titan_multimodal;
#[cfg(feature = "anthropic_claude")]
pub mod anthropic_claude;
#[cfg(feature = "baidu_bge")]
pub mod baidu_bge;
#[cfg(feature = "baidu_embedding")]
pub mod baidu_embedding;
#[cfg(feature = "baidu_ernie_embed")]
pub mod baidu_ernie_embed;
#[cfg(feature = "bedrock_amazon_titan_v2")]
pub mod bedrock_amazon_titan_v2;
#[cfg(feature = "bedrock_anthropic_claude")]
pub mod bedrock_anthropic_claude;
#[cfg(feature = "bedrock_cohere_multilingual")]
pub mod bedrock_cohere_multilingual;
#[cfg(feature = "bedrock_cohere_english")]
pub mod bedrock_cohere_english;
#[cfg(feature = "bedrock_llama_guard")]
pub mod bedrock_llama_guard;
#[cfg(feature = "bedrock_mistral_embed")]
pub mod bedrock_mistral_embed;
#[cfg(feature = "bedrock_stability_embed")]
pub mod bedrock_stability_embed;
#[cfg(feature = "bedrock_titan_multimodal_v2")]
pub mod bedrock_titan_multimodal_v2;
#[cfg(feature = "bytedance_embed")]
pub mod bytedance_embed;
#[cfg(feature = "cohere_embed_english_v3")]
pub mod cohere_embed_english_v3;
#[cfg(feature = "cohere_embed_multilingual_v3")]
pub mod cohere_embed_multilingual_v3;
#[cfg(feature = "cohere_embed_light")]
pub mod cohere_embed_light;
#[cfg(feature = "cohere_embed_english_v2")]
pub mod cohere_embed_english_v2;
#[cfg(feature = "databricks_bge")]
pub mod databricks_bge;
#[cfg(feature = "deepinfra_bge")]
pub mod deepinfra_bge;
#[cfg(feature = "deepinfra_e5")]
pub mod deepinfra_e5;
#[cfg(feature = "deepinfra_gte")]
pub mod deepinfra_gte;
#[cfg(feature = "google_bert")]
pub mod google_bert;
#[cfg(feature = "google_gecko_multilingual")]
pub mod google_gecko_multilingual;
#[cfg(feature = "google_gecko_text")]
pub mod google_gecko_text;
