//! LLM provider implementations — OpenAI, Anthropic, Google, and many more.
//!
//! Each provider module is gated behind a feature flag. The common interfaces
//! are defined in [`traits`] with shared types in [`types`]. Re-exports of
//! all providers are available via [`providers`].

pub mod traits;
pub mod types;
pub mod providers;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "anthropic")]
pub mod anthropic;
#[cfg(feature = "google")]
pub mod google;
#[cfg(feature = "cohere")]
pub mod cohere;
#[cfg(feature = "mistral")]
pub mod mistral;
#[cfg(feature = "groq")]
pub mod groq;
#[cfg(feature = "ollama")]
pub mod ollama;
#[cfg(feature = "azure")]
pub mod azure;
#[cfg(feature = "bedrock")]
pub mod bedrock;
#[cfg(feature = "together")]
pub mod together;
#[cfg(feature = "fireworks")]
pub mod fireworks;
#[cfg(feature = "deepseek")]
pub mod deepseek;
#[cfg(feature = "perplexity")]
pub mod perplexity;
#[cfg(feature = "replicate")]
pub mod replicate;
#[cfg(feature = "huggingface")]
pub mod huggingface;
#[cfg(feature = "xai")]
pub mod xai;
#[cfg(feature = "openrouter")]
pub mod openrouter;
#[cfg(feature = "ai21")]
pub mod ai21;
#[cfg(feature = "cerebras")]
pub mod cerebras;
#[cfg(feature = "nvidia")]
pub mod nvidia;
#[cfg(feature = "sambanova")]
pub mod sambanova;
#[cfg(feature = "databricks")]
pub mod databricks;
#[cfg(feature = "litellm")]
pub mod litellm;
#[cfg(feature = "localai")]
pub mod localai;
#[cfg(feature = "llamacpp")]
pub mod llamacpp;
#[cfg(feature = "gpt4all")]
pub mod gpt4all;
#[cfg(feature = "watsonx")]
pub mod watsonx;
#[cfg(feature = "vllm")]
pub mod vllm;
#[cfg(feature = "tongyi")]
pub mod tongyi;
#[cfg(feature = "qianfan")]
pub mod qianfan;
#[cfg(feature = "sagemaker")]
pub mod sagemaker;
#[cfg(feature = "octoai")]
pub mod octoai;
#[cfg(feature = "deepinfra")]
pub mod deepinfra;
#[cfg(feature = "writer")]
pub mod writer;
#[cfg(feature = "anyscale")]
pub mod anyscale;
#[cfg(feature = "googlestorage")]
pub mod googlestorage;
#[cfg(feature = "claude")]
pub mod claude;
#[cfg(feature = "bedrock_cohere")]
pub mod bedrock_cohere;
#[cfg(feature = "bedrock_ai21")]
pub mod bedrock_ai21;
#[cfg(feature = "alephalpha")]
pub mod alephalpha;
#[cfg(feature = "forefront")]
pub mod forefront;
#[cfg(feature = "gooseai")]
pub mod gooseai;
#[cfg(feature = "huggingface_hub")]
pub mod huggingface_hub;
#[cfg(feature = "koboldai")]
pub mod koboldai;
#[cfg(feature = "nlplanet")]
pub mod nlplanet;
#[cfg(feature = "petals")]
pub mod petals;
#[cfg(feature = "predibase")]
pub mod predibase;
#[cfg(feature = "banana")]
pub mod banana;
#[cfg(feature = "modal")]
pub mod modal;
#[cfg(feature = "spell")]
pub mod spell;
#[cfg(feature = "stepfun")]
pub mod stepfun;
#[cfg(feature = "hunyuan")]
pub mod hunyuan;
#[cfg(feature = "lingyiwanwu")]
pub mod lingyiwanwu;
#[cfg(feature = "sparkdesk")]
pub mod sparkdesk;
#[cfg(feature = "ernie_bot")]
pub mod ernie_bot;
#[cfg(feature = "promptlayer")]
pub mod promptlayer;
#[cfg(feature = "stochasticai")]
pub mod stochasticai;
#[cfg(feature = "outlines")]
pub mod outlines;
#[cfg(feature = "textgen")]
pub mod textgen;
#[cfg(feature = "openai_community")]
pub mod openai_community;
#[cfg(feature = "cloudflare_workers")]
pub mod cloudflare_workers;
#[cfg(feature = "google_palm")]
pub mod google_palm;
#[cfg(feature = "coze")]
pub mod coze;
#[cfg(feature = "minimax")]
pub mod minimax;
#[cfg(feature = "zhipuai")]
pub mod zhipuai;
#[cfg(feature = "bedrock_anthropic")]
pub mod bedrock_anthropic;
#[cfg(feature = "bedrock_meta")]
pub mod bedrock_meta;
#[cfg(feature = "bedrock_stabilityai")]
pub mod bedrock_stabilityai;
#[cfg(feature = "bedrock_mistral")]
pub mod bedrock_mistral;
#[cfg(feature = "bedrock_amazon")]
pub mod bedrock_amazon;
#[cfg(feature = "microsoft_openai")]
pub mod microsoft_openai;
#[cfg(feature = "databricks_llm")]
pub mod databricks_llm;
#[cfg(feature = "fireworks_v2")]
pub mod fireworks_v2;
#[cfg(feature = "together_v2")]
pub mod together_v2;
#[cfg(feature = "deepinfra_v2")]
pub mod deepinfra_v2;
#[cfg(feature = "anyscale_v2")]
pub mod anyscale_v2;
#[cfg(feature = "perplexity_v2")]
pub mod perplexity_v2;
#[cfg(feature = "replicate_v2")]
pub mod replicate_v2;
#[cfg(feature = "huggingface_v2")]
pub mod huggingface_v2;
#[cfg(feature = "openrouter_v2")]
pub mod openrouter_v2;
#[cfg(feature = "ai21_v2")]
pub mod ai21_v2;
#[cfg(feature = "cohere_v2")]
pub mod cohere_v2;
#[cfg(feature = "mistral_v2")]
pub mod mistral_v2;
#[cfg(feature = "groq_v2")]
pub mod groq_v2;
#[cfg(feature = "google_v2")]
pub mod google_v2;
#[cfg(feature = "bedrock_claude_v3")]
pub mod bedrock_claude_v3;
#[cfg(feature = "bedrock_llama_v3")]
pub mod bedrock_llama_v3;
#[cfg(feature = "bedrock_jurassic2")]
pub mod bedrock_jurassic2;
#[cfg(feature = "bedrock_command")]
pub mod bedrock_command;
#[cfg(feature = "bedrock_titan_v2")]
pub mod bedrock_titan_v2;
#[cfg(feature = "bedrock_nova")]
pub mod bedrock_nova;
#[cfg(feature = "bedrock_mistral_v2")]
pub mod bedrock_mistral_v2;
#[cfg(feature = "bedrock_stable_diffusion")]
pub mod bedrock_stable_diffusion;
#[cfg(feature = "gpt4all_v2")]
pub mod gpt4all_v2;
#[cfg(feature = "llamacpp_v2")]
pub mod llamacpp_v2;
#[cfg(feature = "ollama_v2")]
pub mod ollama_v2;
#[cfg(feature = "ollama_custom")]
pub mod ollama_custom;
#[cfg(feature = "groq_mixtral")]
pub mod groq_mixtral;
#[cfg(feature = "groq_llama")]
pub mod groq_llama;
#[cfg(feature = "groq_gemma")]
pub mod groq_gemma;
#[cfg(feature = "anthropic_claude_v3")]
pub mod anthropic_claude_v3;
#[cfg(feature = "anthropic_claude_v4")]
pub mod anthropic_claude_v4;
#[cfg(feature = "openai_gpt4")]
pub mod openai_gpt4;
#[cfg(feature = "openai_gpt4o")]
pub mod openai_gpt4o;
#[cfg(feature = "openai_o1")]
pub mod openai_o1;
#[cfg(feature = "openai_o3")]
pub mod openai_o3;
#[cfg(feature = "google_gemini")]
pub mod google_gemini;
#[cfg(feature = "google_gemini_v2")]
pub mod google_gemini_v2;
#[cfg(feature = "google_gemini_flash")]
pub mod google_gemini_flash;
#[cfg(feature = "google_gemini_pro")]
pub mod google_gemini_pro;
#[cfg(feature = "mistral_large")]
pub mod mistral_large;
#[cfg(feature = "mistral_small")]
pub mod mistral_small;
#[cfg(feature = "mistral_medium")]
pub mod mistral_medium;
#[cfg(feature = "cohere_command")]
pub mod cohere_command;
#[cfg(feature = "cohere_command_r")]
pub mod cohere_command_r;
#[cfg(feature = "acme")]
pub mod acme;
#[cfg(feature = "ai21_labs")]
pub mod ai21_labs;
#[cfg(feature = "ai21_jurassic")]
pub mod ai21_jurassic;
#[cfg(feature = "ai21_jurassic2_large")]
pub mod ai21_jurassic2_large;
#[cfg(feature = "ai21_jurassic2_mid")]
pub mod ai21_jurassic2_mid;
#[cfg(feature = "ai21_jurassic2_ultra")]
pub mod ai21_jurassic2_ultra;
#[cfg(feature = "alibaba_qwen")]
pub mod alibaba_qwen;
#[cfg(feature = "alibaba_qwen_turbo")]
pub mod alibaba_qwen_turbo;
#[cfg(feature = "alibaba_qwen_plus")]
pub mod alibaba_qwen_plus;
#[cfg(feature = "alibaba_qwen_max")]
pub mod alibaba_qwen_max;
#[cfg(feature = "alibaba_qwen2")]
pub mod alibaba_qwen2;
#[cfg(feature = "alibaba_qwen2_5")]
pub mod alibaba_qwen2_5;
#[cfg(feature = "alibaba_qwen2_5_72b")]
pub mod alibaba_qwen2_5_72b;
#[cfg(feature = "alibaba_qwen_coder")]
pub mod alibaba_qwen_coder;
#[cfg(feature = "alibaba_qwen_vl")]
pub mod alibaba_qwen_vl;
#[cfg(feature = "alibaba_qwen_audio")]
pub mod alibaba_qwen_audio;
#[cfg(feature = "amazon_nova_lite")]
pub mod amazon_nova_lite;
#[cfg(feature = "amazon_nova_pro")]
pub mod amazon_nova_pro;
#[cfg(feature = "amazon_nova_micro")]
pub mod amazon_nova_micro;
#[cfg(feature = "anthropic_claude_2")]
pub mod anthropic_claude_2;
#[cfg(feature = "anthropic_claude_2_1")]
pub mod anthropic_claude_2_1;
#[cfg(feature = "anthropic_claude_3_haiku")]
pub mod anthropic_claude_3_haiku;
#[cfg(feature = "anthropic_claude_3_sonnet")]
pub mod anthropic_claude_3_sonnet;
#[cfg(feature = "anthropic_claude_3_opus")]
pub mod anthropic_claude_3_opus;
#[cfg(feature = "anthropic_claude_3_5_sonnet")]
pub mod anthropic_claude_3_5_sonnet;
#[cfg(feature = "anthropic_claude_3_5_haiku")]
pub mod anthropic_claude_3_5_haiku;
#[cfg(feature = "google_gemini_1_5_pro")]
pub mod google_gemini_1_5_pro;
#[cfg(feature = "google_gemini_1_5_flash")]
pub mod google_gemini_1_5_flash;
#[cfg(feature = "google_gemini_2_0_pro")]
pub mod google_gemini_2_0_pro;
#[cfg(feature = "deepseek_coder_v2")]
pub mod deepseek_coder_v2;
#[cfg(feature = "abacus")]
pub mod abacus;
#[cfg(feature = "abzu")]
pub mod abzu;
#[cfg(feature = "adaline")]
pub mod adaline;
#[cfg(feature = "adobe")]
pub mod adobe;
#[cfg(feature = "aether")]
pub mod aether;
#[cfg(feature = "ai21_jamba")]
pub mod ai21_jamba;
#[cfg(feature = "ai21_jamba_instruct")]
pub mod ai21_jamba_instruct;
#[cfg(feature = "allenai")]
pub mod allenai;
#[cfg(feature = "allenai_olmo")]
pub mod allenai_olmo;
#[cfg(feature = "allenai_tulu")]
pub mod allenai_tulu;
#[cfg(feature = "anthropic_claude_3_opus_2024")]
pub mod anthropic_claude_3_opus_2024;
#[cfg(feature = "anthropic_claude_3_sonnet_2024")]
pub mod anthropic_claude_3_sonnet_2024;
#[cfg(feature = "anthropic_claude_3_haiku_2024")]
pub mod anthropic_claude_3_haiku_2024;
#[cfg(feature = "anthropic_claude_3_5_sonnet_2025")]
pub mod anthropic_claude_3_5_sonnet_2025;
#[cfg(feature = "anthropic_claude_3_5_haiku_2025")]
pub mod anthropic_claude_3_5_haiku_2025;
#[cfg(feature = "anthropic_claude_4_opus")]
pub mod anthropic_claude_4_opus;
#[cfg(feature = "anthropic_claude_4_sonnet")]
pub mod anthropic_claude_4_sonnet;
#[cfg(feature = "anthropic_claude_4_haiku")]
pub mod anthropic_claude_4_haiku;
#[cfg(feature = "arcee")]
pub mod arcee;
#[cfg(feature = "arcee_fuse")]
pub mod arcee_fuse;
#[cfg(feature = "arctic")]
pub mod arctic;
#[cfg(feature = "atlas_llm")]
pub mod atlas_llm;
#[cfg(feature = "aviary")]
pub mod aviary;
#[cfg(feature = "banana_dev")]
pub mod banana_dev;
#[cfg(feature = "bedrock_claude_3")]
pub mod bedrock_claude_3;
#[cfg(feature = "bedrock_claude_3_5")]
pub mod bedrock_claude_3_5;
#[cfg(feature = "bedrock_claude_4")]
pub mod bedrock_claude_4;
#[cfg(feature = "bedrock_llama_3")]
pub mod bedrock_llama_3;
#[cfg(feature = "bedrock_llama_3_1")]
pub mod bedrock_llama_3_1;
#[cfg(feature = "bedrock_llama_3_2")]
pub mod bedrock_llama_3_2;
#[cfg(feature = "bedrock_mistral_large")]
pub mod bedrock_mistral_large;
#[cfg(feature = "bedrock_mistral_small")]
pub mod bedrock_mistral_small;
#[cfg(feature = "bedrock_ai21_jamba")]
pub mod bedrock_ai21_jamba;
#[cfg(feature = "bedrock_ai21_jurassic")]
pub mod bedrock_ai21_jurassic;
#[cfg(feature = "bedrock_titan_text")]
pub mod bedrock_titan_text;
#[cfg(feature = "bigcode")]
pub mod bigcode;
#[cfg(feature = "bloom")]
pub mod bloom;
#[cfg(feature = "bloomz")]
pub mod bloomz;
#[cfg(feature = "chatglm")]
pub mod chatglm;
#[cfg(feature = "chatglm2")]
pub mod chatglm2;
#[cfg(feature = "chatglm3")]
pub mod chatglm3;
#[cfg(feature = "chatglm4")]
pub mod chatglm4;
#[cfg(feature = "chatgpt_4o")]
pub mod chatgpt_4o;
#[cfg(feature = "chatgpt_4o_mini")]
pub mod chatgpt_4o_mini;
#[cfg(feature = "chatgpt_o1")]
pub mod chatgpt_o1;
#[cfg(feature = "chatgpt_o1_mini")]
pub mod chatgpt_o1_mini;
#[cfg(feature = "chatgpt_o3")]
pub mod chatgpt_o3;
#[cfg(feature = "chatgpt_o3_mini")]
pub mod chatgpt_o3_mini;
#[cfg(feature = "code_llama")]
pub mod code_llama;
#[cfg(feature = "code_llama_70b")]
pub mod code_llama_70b;
pub mod fake;
